language: node_js
node_js: 12
script:
- npx semantic-release
env:
  global:
    secure: l4u629KfNXGCzY9IY6pvihNqreYbrToJ+zCMPG12EtgOd5xI6ukPx9dEWcBobWi2TBgAsOXxw16usrMXvZLGqw+4dg5UYaJnah/G3eLUGMKitNqUhdJdRzUCynfJ3QCmtUqSJz6HOEVsRw+DnKpxjuiNNQ0BigdPSDoyuiyo4Ex7QQ4iS8HKzmaBX5bSDAZrJUd+JpmHhO1fms+wQU5B2mVDPPNgPKeCKOm9fpbDQW4vuEc301sWWiXuv3MGQe5uLoq1Cyajmv4JZn4VsyMqZgQoH0JeMypHPSYoIjaeoq7kABRE1mjR/olhwF7NQa3ZcRnRlIpk8+Ph6zNMfZqYiG7HAoUEQR0OfY7aVMNu91XiDumkj/uNhnsYtxpE4sZynHhNwZDLlSEuJEHvEoFeh613wDuS1db3P21EwR6uNuFScpviFFF7lyEM9PR8fYOUxE4Ej2XPH1VsL6XOKU+LgWXebD1nMqqAfZzehZ7HNZMRtxWcPSuizW4e/UVB6qsLp7mfvDHzH8BbFiJ8PV/yGmsmArltZf+avz6WcNPxnXLBZdBS1fabo8jgOrKsLwadz9/ZZeeaQGu5XQJdQcaY7G0/u+mIb+3c88/98LfF31FHknad/srSFCeciQvFRIav+0InLdPP3ch33kqsDTEbny6LtU+LaaqRvensbmM8dJI=
